table Dim_Date
	lineageTag: 908efcc7-b113-47b5-a45b-8868a1d0a896

	column Date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 8ee720eb-73ad-435f-98de-4976193d41ed
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic
		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 5487eba3-2e70-4184-a644-4892f8edb2c7
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 8ac53197-e080-4270-90c2-56bf56c0563b
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 75d251e5-239f-4cfc-a885-b056aaa40dc3
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column ReportingPeriod
		dataType: string
		lineageTag: 6a51dd14-ded9-41c3-93a8-588880cb0b6b
		summarizeBy: none
		sourceColumn: ReportingPeriod

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 3d5f4d3e-0200-430e-b803-0b3ef5dcfd47
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	partition Dim_Date-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Dim_Date.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"Date", type datetime},
				        {"Year", Int64.Type},
				        {"Month", Int64.Type},
				        {"MonthName", type text},
				        {"ReportingPeriod", type text},
				        {"Quarter", Int64.Type}
				    })
				in
				    #"Changed Type"
