table Dim_Project
	lineageTag: d78264c7-c5a9-4518-9c8c-fc03d6ead028

	column project_id
		dataType: string
		lineageTag: 1289f338-3302-4807-a2d2-6cbdfe59658f
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column project_name
		dataType: string
		lineageTag: 195ed310-5805-4331-b444-a5d3d752797a
		summarizeBy: none
		sourceColumn: project_name

		annotation SummarizationSetBy = Automatic

	column bac
		dataType: double
		formatString: #,##0
		lineageTag: 77f36fa8-afc0-4224-9a88-84a3e27e7f11
		summarizeBy: sum
		sourceColumn: bac

		annotation SummarizationSetBy = Automatic

	column pv
		dataType: double
		formatString: #,##0
		lineageTag: 5e50b0ce-aa54-4e34-84a2-2cb1ac7804ea
		summarizeBy: sum
		sourceColumn: pv

		annotation SummarizationSetBy = Automatic

	column ev
		dataType: double
		formatString: #,##0
		lineageTag: e1c3737a-8af9-4d59-802b-46d29ebedf15
		summarizeBy: sum
		sourceColumn: ev

		annotation SummarizationSetBy = Automatic

	column ac
		dataType: double
		formatString: #,##0
		lineageTag: 101013d6-5456-4be2-98b7-fc640ca7f42a
		summarizeBy: sum
		sourceColumn: ac

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 3af00e3c-cc67-415d-93f8-0486fedbba5e
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition Dim_Project-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Dim_Project.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"project_id", type text},
				        {"project_name", type text},
				        {"bac", type number},
				        {"pv", type number},
				        {"ev", type number},
				        {"ac", type number},
				        {"status", type text}
				    })
				in
				    #"Changed Type"
