table Dim_Date
	lineageTag: bca65794-f1ae-45e8-960d-40dc5ea6be2d

	column Date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: a4db2f45-6937-4439-b5a6-6812b33dc3eb
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic
		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 9c19cd47-74bb-42ff-95c5-ad6a6a3904d9
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: b93bb69a-2518-447c-9714-ce79149f0acf
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 5d3d4e81-0909-4527-a54b-6d6bddc7a21c
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column ReportingPeriod
		dataType: string
		lineageTag: fadc251b-fd4f-4498-b03d-f7b70fe10b57
		summarizeBy: none
		sourceColumn: ReportingPeriod

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 90aef265-f69c-4638-8633-b084a981849f
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	partition Dim_Date-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Dim_Date.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"Date", type datetime},
				        {"Year", Int64.Type},
				        {"Month", Int64.Type},
				        {"MonthName", type text},
				        {"ReportingPeriod", type text},
				        {"Quarter", Int64.Type}
				    })
				in
				    #"Changed Type"
