table Dim_Date
	lineageTag: 65037db5-a3a4-414a-9f0f-4dbc324a36d6

	column Date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 743f0f21-62cb-4ae6-b090-dbac92a25371
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 1451b428-224e-403b-8035-7918e046a67a
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 62db6a0b-4d71-48e1-915a-f7b475f9a263
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: cd8285bf-e84f-421d-98e3-1d556423b3da
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column ReportingPeriod
		dataType: string
		lineageTag: daf7dd57-b65f-416c-b040-0c903746a392
		summarizeBy: none
		sourceColumn: ReportingPeriod

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 7ef4da3f-ca80-4b02-81aa-488240896ac4
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	partition Dim_Date-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Dim_Date.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"Date", type datetime},
				        {"Year", Int64.Type},
				        {"Month", Int64.Type},
				        {"MonthName", type text},
				        {"ReportingPeriod", type text},
				        {"Quarter", Int64.Type}
				    })
				in
				    #"Changed Type"

