table Dim_Project
	lineageTag: 4b8a4eec-9842-4858-9ba0-b639a8c5afef

	column project_id
		dataType: string
		lineageTag: a8555dec-b78d-4766-84e5-4b6262b37ce9
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column project_name
		dataType: string
		lineageTag: ff26f59c-98f6-423f-98db-9bc747fdd7b0
		summarizeBy: none
		sourceColumn: project_name

		annotation SummarizationSetBy = Automatic

	column bac
		dataType: double
		formatString: #,##0
		lineageTag: d07fbae7-1c5e-4212-9e50-92d8f23234c6
		summarizeBy: sum
		sourceColumn: bac

		annotation SummarizationSetBy = Automatic

	column pv
		dataType: double
		formatString: #,##0
		lineageTag: 1f99254a-ed6e-473f-8f8e-fbdd785684cb
		summarizeBy: sum
		sourceColumn: pv

		annotation SummarizationSetBy = Automatic

	column ev
		dataType: double
		formatString: #,##0
		lineageTag: ada6b9e4-4478-4461-b077-48a3babd3ff1
		summarizeBy: sum
		sourceColumn: ev

		annotation SummarizationSetBy = Automatic

	column ac
		dataType: double
		formatString: #,##0
		lineageTag: 5343a28e-8078-419d-91de-bec5de7f0c61
		summarizeBy: sum
		sourceColumn: ac

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: cacc4634-2d0a-4638-9d2b-fba666892578
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition Dim_Project-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Dim_Project.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"project_id", type text},
				        {"project_name", type text},
				        {"bac", type number},
				        {"pv", type number},
				        {"ev", type number},
				        {"ac", type number},
				        {"status", type text}
				    })
				in
				    #"Changed Type"
