table Dim_Date
	lineageTag: 08f130de-12ba-4598-a18a-5772ebb7e71b

	column Date
		dataType: dateTime
		formatString: yyyy-MM-dd
		lineageTag: 318831ac-08c9-4d2b-85e7-4ae6b79ff1b3
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic
		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: e543f08c-ced7-4fc2-a520-4f76c95a0813
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 6c90b10b-373d-487b-b907-6819fa8d0aa0
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: f0fea11a-8f9b-4b90-bdf3-023eeb35ac52
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column ReportingPeriod
		dataType: string
		lineageTag: 52985958-6165-4bcd-bda1-d3f7661d820e
		summarizeBy: none
		sourceColumn: ReportingPeriod

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 18691d32-9db0-4089-adca-ab218df263b5
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	partition Dim_Date-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Dim_Date.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"Date", type datetime},
				        {"Year", Int64.Type},
				        {"Month", Int64.Type},
				        {"MonthName", type text},
				        {"ReportingPeriod", type text},
				        {"Quarter", Int64.Type}
				    })
				in
				    #"Changed Type"
