table Dim_Project
	lineageTag: 1592eb2a-7680-429b-906b-60a1cedb1ff9

	column project_id
		dataType: string
		lineageTag: 028cca2f-3ad8-4d95-b3f1-ea58f46804c1
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column project_name
		dataType: string
		lineageTag: b8711a9d-6cb4-4d6e-9d68-93de414b4a12
		summarizeBy: none
		sourceColumn: project_name

		annotation SummarizationSetBy = Automatic

	column bac
		dataType: double
		formatString: #,##0
		lineageTag: 285527a2-8da4-4863-a124-e184ff3a69b5
		summarizeBy: sum
		sourceColumn: bac

		annotation SummarizationSetBy = Automatic

	column pv
		dataType: double
		formatString: #,##0
		lineageTag: cd274af8-2278-44d2-9142-0b0002f39944
		summarizeBy: sum
		sourceColumn: pv

		annotation SummarizationSetBy = Automatic

	column ev
		dataType: double
		formatString: #,##0
		lineageTag: 93268271-b73f-4aec-89be-3d8142c47bd8
		summarizeBy: sum
		sourceColumn: ev

		annotation SummarizationSetBy = Automatic

	column ac
		dataType: double
		formatString: #,##0
		lineageTag: 821b609d-2eb4-4436-88f4-1c37263f49bd
		summarizeBy: sum
		sourceColumn: ac

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 543e76d7-e9ea-4419-9fc7-65c0cd13194b
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition Dim_Project-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Dim_Project.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"project_id", type text},
				        {"project_name", type text},
				        {"bac", type number},
				        {"pv", type number},
				        {"ev", type number},
				        {"ac", type number},
				        {"status", type text}
				    })
				in
				    #"Changed Type"
