table Fact_EVM_Snapshots
	lineageTag: de18b5a6-4f84-4d0d-bcc7-9faa75a50705

	column reporting_period
		dataType: string
		lineageTag: 2c05c642-4324-415f-af1d-da0e997dc47b
		summarizeBy: none
		sourceColumn: reporting_period

		annotation SummarizationSetBy = Automatic

	column snapshot_timestamp
		dataType: dateTime
		formatString: yyyy-MM-dd HH:mm:ss
		lineageTag: 5b558508-edc1-4479-9558-bf7b5180ea30
		summarizeBy: none
		sourceColumn: snapshot_timestamp

		annotation SummarizationSetBy = Automatic

	column project_id
		dataType: string
		lineageTag: d794acd0-f5ca-4e20-9c74-8d4545710400
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column bac
		dataType: double
		formatString: #,##0
		lineageTag: c7078612-006e-457c-af6e-c3403eba7fcb
		summarizeBy: sum
		sourceColumn: bac

		annotation SummarizationSetBy = Automatic

	column pv
		dataType: double
		formatString: #,##0
		lineageTag: 2f7811c4-6c5a-4050-ba26-07c73f3f95ec
		summarizeBy: sum
		sourceColumn: pv

		annotation SummarizationSetBy = Automatic

	column ev
		dataType: double
		formatString: #,##0
		lineageTag: c647faa3-dfaa-4297-b946-1a512d66d458
		summarizeBy: sum
		sourceColumn: ev

		annotation SummarizationSetBy = Automatic

	column ac
		dataType: double
		formatString: #,##0
		lineageTag: 2bc60729-ad25-4545-8cba-5589371027b6
		summarizeBy: sum
		sourceColumn: ac

		annotation SummarizationSetBy = Automatic

	column cpi
		dataType: double
		formatString: 0.00
		lineageTag: 12f65e14-c0a1-4ff8-86f5-8fe28997780f
		summarizeBy: average
		sourceColumn: cpi

		annotation SummarizationSetBy = Automatic

	column spi
		dataType: double
		formatString: 0.00
		lineageTag: 4251a396-edb0-4a8c-bec2-9145f4b1288c
		summarizeBy: average
		sourceColumn: spi

		annotation SummarizationSetBy = Automatic

	column eac_cpi
		dataType: double
		formatString: #,##0
		lineageTag: 44511802-fcaf-43e0-8c82-6b53799fe0b9
		summarizeBy: sum
		sourceColumn: eac_cpi

		annotation SummarizationSetBy = Automatic

	column eac_composite
		dataType: double
		formatString: #,##0
		lineageTag: ffe89a68-cf4b-4945-be40-30bbc377171c
		summarizeBy: sum
		sourceColumn: eac_composite

		annotation SummarizationSetBy = Automatic

	column eac_weighted
		dataType: double
		formatString: #,##0
		lineageTag: 8d45f908-ff96-4413-a249-8696d0be4f2b
		summarizeBy: sum
		sourceColumn: eac_weighted

		annotation SummarizationSetBy = Automatic

	column vac
		dataType: double
		formatString: #,##0
		lineageTag: 41b03697-f87e-4879-96e1-0bfd2abe9340
		summarizeBy: sum
		sourceColumn: vac

		annotation SummarizationSetBy = Automatic

	column tcpi
		dataType: double
		formatString: 0.00
		lineageTag: befdac0f-eaec-454d-8cf6-a69040f90042
		summarizeBy: average
		sourceColumn: tcpi

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: e772a339-a40e-46d7-9d2b-337503e51331
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition Fact_EVM_Snapshots-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Fact_EVM_Snapshots.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"reporting_period", type text},
				        {"snapshot_timestamp", type datetime},
				        {"project_id", type text},
				        {"bac", type number},
				        {"pv", type number},
				        {"ev", type number},
				        {"ac", type number},
				        {"cpi", type number},
				        {"spi", type number},
				        {"eac_cpi", type number},
				        {"eac_composite", type number},
				        {"eac_weighted", type number},
				        {"vac", type number},
				        {"tcpi", type number},
				        {"status", type text}
				    })
				in
				    #"Changed Type"
