table Fact_EVM_Snapshots
	lineageTag: cee5aff8-b2db-4032-a2fd-74993a9c9626

	column reporting_period
		dataType: string
		lineageTag: bd5ea13f-5251-4411-8e0a-f9f5f24390c3
		summarizeBy: none
		sourceColumn: reporting_period

		annotation SummarizationSetBy = Automatic

	column snapshot_timestamp
		dataType: dateTime
		formatString: yyyy-MM-dd HH:mm:ss
		lineageTag: 9f6727c7-ac97-4846-adaf-b59445e856a6
		summarizeBy: none
		sourceColumn: snapshot_timestamp

		annotation SummarizationSetBy = Automatic

	column project_id
		dataType: string
		lineageTag: 20152def-c191-4002-bfbe-831c98ec11e1
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column bac
		dataType: double
		formatString: #,##0
		lineageTag: cf9036ac-53ae-4217-ac77-e821da4a61a2
		summarizeBy: sum
		sourceColumn: bac

		annotation SummarizationSetBy = Automatic

	column pv
		dataType: double
		formatString: #,##0
		lineageTag: de7f1235-fe4e-4022-88a1-add2c3c4a2de
		summarizeBy: sum
		sourceColumn: pv

		annotation SummarizationSetBy = Automatic

	column ev
		dataType: double
		formatString: #,##0
		lineageTag: b467889a-3028-4aec-b16b-cab65bad784d
		summarizeBy: sum
		sourceColumn: ev

		annotation SummarizationSetBy = Automatic

	column ac
		dataType: double
		formatString: #,##0
		lineageTag: 91a0afa8-0984-477d-967a-d942404de7c2
		summarizeBy: sum
		sourceColumn: ac

		annotation SummarizationSetBy = Automatic

	column cpi
		dataType: double
		formatString: 0.00
		lineageTag: 0dec70e0-4daa-44ea-8763-a42892fc289d
		summarizeBy: average
		sourceColumn: cpi

		annotation SummarizationSetBy = Automatic

	column spi
		dataType: double
		formatString: 0.00
		lineageTag: a23cdeb6-3228-405d-b08e-f70cf60fd632
		summarizeBy: average
		sourceColumn: spi

		annotation SummarizationSetBy = Automatic

	column eac_cpi
		dataType: double
		formatString: #,##0
		lineageTag: 305afd0f-cd39-4755-9b11-9f413e3f81ca
		summarizeBy: sum
		sourceColumn: eac_cpi

		annotation SummarizationSetBy = Automatic

	column eac_composite
		dataType: double
		formatString: #,##0
		lineageTag: a8f477d8-09dd-4480-905d-e4e19cc6471a
		summarizeBy: sum
		sourceColumn: eac_composite

		annotation SummarizationSetBy = Automatic

	column eac_weighted
		dataType: double
		formatString: #,##0
		lineageTag: c2618d68-b52b-4b8a-b7bb-c962e33b093d
		summarizeBy: sum
		sourceColumn: eac_weighted

		annotation SummarizationSetBy = Automatic

	column vac
		dataType: double
		formatString: #,##0
		lineageTag: 8cbe24a0-7cc4-4ee1-980b-e86ae9a8538b
		summarizeBy: sum
		sourceColumn: vac

		annotation SummarizationSetBy = Automatic

	column tcpi
		dataType: double
		formatString: 0.00
		lineageTag: cb2d0134-3ca2-4501-be02-397a4afb4a26
		summarizeBy: average
		sourceColumn: tcpi

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: e4adebdb-24ff-4a3e-8dd2-736d17aff129
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition Fact_EVM_Snapshots-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Fact_EVM_Snapshots.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"reporting_period", type text},
				        {"snapshot_timestamp", type datetime},
				        {"project_id", type text},
				        {"bac", type number},
				        {"pv", type number},
				        {"ev", type number},
				        {"ac", type number},
				        {"cpi", type number},
				        {"spi", type number},
				        {"eac_cpi", type number},
				        {"eac_composite", type number},
				        {"eac_weighted", type number},
				        {"vac", type number},
				        {"tcpi", type number},
				        {"status", type text}
				    })
				in
				    #"Changed Type"
