table Fact_Travel_Audit
	lineageTag: e42b2545-d743-4a4b-8fa6-3a9d1d097e13

	column Reise_ID
		dataType: string
		lineageTag: 642d807d-92e0-439c-8a29-46ed5eeebf21
		summarizeBy: none
		sourceColumn: Reise_ID

		annotation SummarizationSetBy = Automatic

	column Ansatt
		dataType: string
		lineageTag: 69865e23-d685-4651-9f90-3811e158307c
		summarizeBy: none
		sourceColumn: Ansatt

		annotation SummarizationSetBy = Automatic

	column Dato
		dataType: string
		lineageTag: 929a8e23-d363-47e6-a32c-71f2a6952106
		summarizeBy: none
		sourceColumn: Dato

		annotation SummarizationSetBy = Automatic

	column Formaal
		dataType: string
		lineageTag: 3f4c9e3f-88f1-4985-b8c4-b72fb4b73123
		summarizeBy: none
		sourceColumn: Formaal

		annotation SummarizationSetBy = Automatic

	column Belop_NOK
		dataType: double
		formatString: #,##0
		lineageTag: 818988ca-f3fa-4866-bd2f-689a0b8b1e1d
		summarizeBy: sum
		sourceColumn: Belop_NOK

		annotation SummarizationSetBy = Automatic

	column Maltid_Dekket
		dataType: string
		lineageTag: 6a8f6f19-60ed-4aa9-ba3d-c56f679ea64b
		summarizeBy: none
		sourceColumn: Maltid_Dekket

		annotation SummarizationSetBy = Automatic

	column Fradrag_Utfort
		dataType: boolean
		lineageTag: 924232d2-dfba-4aa9-8992-a8905a69fa88
		summarizeBy: none
		sourceColumn: Fradrag_Utfort

		annotation SummarizationSetBy = Automatic

	column Km_Godtgjorelse
		dataType: int64
		formatString: #,##0
		lineageTag: 0bba403d-b940-4bdf-8760-f3dddc0d4f52
		summarizeBy: sum
		sourceColumn: Km_Godtgjorelse

		annotation SummarizationSetBy = Automatic

	column Kvittering_Vedlagt
		dataType: boolean
		lineageTag: 92d9a7d3-6096-4656-be1d-4dce1c88cce4
		summarizeBy: none
		sourceColumn: Kvittering_Vedlagt

		annotation SummarizationSetBy = Automatic

	column BDM_ID
		dataType: string
		lineageTag: 3c2f2bd0-cfd9-4202-bf48-d6faed78642e
		summarizeBy: none
		sourceColumn: BDM_ID

		annotation SummarizationSetBy = Automatic

	column Attestant_ID
		dataType: string
		lineageTag: 38218410-14fe-4ff9-9822-25a7fb43a870
		summarizeBy: none
		sourceColumn: Attestant_ID

		annotation SummarizationSetBy = Automatic

	column Km_Rute_Beskrevet
		dataType: boolean
		lineageTag: 94a4e212-9c52-40b2-a148-1b818e050cfc
		summarizeBy: none
		sourceColumn: Km_Rute_Beskrevet

		annotation SummarizationSetBy = Automatic

	column Avvik_Beskrivelse
		dataType: string
		lineageTag: 23288b97-375d-4435-aa3d-7943b64d0b85
		summarizeBy: none
		sourceColumn: Avvik_Beskrivelse

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: e04e1fcc-e1ec-4d3c-b726-79094a5bc7d4
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition Fact_Travel_Audit-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Fact_Travel_Audit.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"Reise_ID", type text},
				        {"Ansatt", type text},
				        {"Dato", type text},
				        {"Formaal", type text},
				        {"Belop_NOK", type number},
				        {"Maltid_Dekket", type text},
				        {"Fradrag_Utfort", type logical},
				        {"Km_Godtgjorelse", Int64.Type},
				        {"Kvittering_Vedlagt", type logical},
				        {"BDM_ID", type text},
				        {"Attestant_ID", type text},
				        {"Km_Rute_Beskrevet", type logical},
				        {"Avvik_Beskrivelse", type text},
				        {"Status", type text}
				    })
				in
				    #"Changed Type"

