table Fact_UBW_Audit
	lineageTag: e08da089-6a2d-4255-a452-db6b718a4484

	column transaksjon_id
		dataType: string
		lineageTag: ff44a101-ed39-4b00-a3db-942c3b9b039c
		summarizeBy: none
		sourceColumn: transaksjon_id

		annotation SummarizationSetBy = Automatic

	column konto
		dataType: string
		lineageTag: 45a3fb6e-9b37-4949-9c08-4d7c7449ccfb
		summarizeBy: none
		sourceColumn: konto

		annotation SummarizationSetBy = Automatic

	column beskrivelse
		dataType: string
		lineageTag: 4c0467bf-2217-4694-836e-e6f53469a1d0
		summarizeBy: none
		sourceColumn: beskrivelse

		annotation SummarizationSetBy = Automatic

	column belop_nok
		dataType: double
		formatString: #,##0
		lineageTag: 02d5b190-3a5e-40f0-a32d-7fb223c7f0d1
		summarizeBy: sum
		sourceColumn: belop_nok

		annotation SummarizationSetBy = Automatic

	column bdm_id
		dataType: string
		lineageTag: 1dd3ae2b-921b-40d9-a2f3-af78f2c357e9
		summarizeBy: none
		sourceColumn: bdm_id

		annotation SummarizationSetBy = Automatic

	column attestant_id
		dataType: string
		lineageTag: 6b99104c-af42-404e-8021-b8ab05d71ef7
		summarizeBy: none
		sourceColumn: attestant_id

		annotation SummarizationSetBy = Automatic

	column kvittering_vedlagt
		dataType: int64
		lineageTag: c2c6bd6b-c408-40c3-b4ca-eec633eac168
		summarizeBy: none
		sourceColumn: kvittering_vedlagt

		annotation SummarizationSetBy = Automatic

	column formaal
		dataType: string
		lineageTag: 947a771a-bb08-4458-b079-2f4a082f7529
		summarizeBy: none
		sourceColumn: formaal

		annotation SummarizationSetBy = Automatic

	column Kontrollflagg
		dataType: string
		lineageTag: 6bad6781-e08a-4bda-9194-2dcfb91890ca
		summarizeBy: none
		sourceColumn: Kontrollflagg

		annotation SummarizationSetBy = Automatic

	partition Fact_UBW_Audit-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Fact_UBW_Audit.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"transaksjon_id", type text},
				        {"konto", type text},
				        {"beskrivelse", type text},
				        {"belop_nok", type number},
				        {"bdm_id", type text},
				        {"attestant_id", type text},
				        {"kvittering_vedlagt", Int64.Type},
				        {"formaal", type text},
				        {"Kontrollflagg", type text}
				    })
				in
				    #"Changed Type"

