table Fact_EVM_Snapshots
	lineageTag: 346a3f47-b0b4-4e96-a361-ef215109fe31

	column reporting_period
		dataType: string
		lineageTag: 035ff639-0384-414a-a894-490b3ff3e801
		summarizeBy: none
		sourceColumn: reporting_period

		annotation SummarizationSetBy = Automatic

	column snapshot_timestamp
		dataType: dateTime
		formatString: yyyy-MM-dd HH:mm:ss
		lineageTag: 8446ac25-e3d5-4f6f-aead-89fe8e2e15b8
		summarizeBy: none
		sourceColumn: snapshot_timestamp

		annotation SummarizationSetBy = Automatic

	column project_id
		dataType: string
		lineageTag: e37f404a-beb0-4313-b9a9-6e684cdb8b3a
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column bac
		dataType: double
		formatString: #,##0
		lineageTag: e870346f-d271-46ce-87a8-0ce2494d9512
		summarizeBy: sum
		sourceColumn: bac

		annotation SummarizationSetBy = Automatic

	column pv
		dataType: double
		formatString: #,##0
		lineageTag: aacc30b8-00d4-4523-9a64-d80285214894
		summarizeBy: sum
		sourceColumn: pv

		annotation SummarizationSetBy = Automatic

	column ev
		dataType: double
		formatString: #,##0
		lineageTag: 3280d41c-ecb3-447a-8b35-5c9ed38dd902
		summarizeBy: sum
		sourceColumn: ev

		annotation SummarizationSetBy = Automatic

	column ac
		dataType: double
		formatString: #,##0
		lineageTag: 73a65799-51b7-4ef8-8949-b56ffe0583a6
		summarizeBy: sum
		sourceColumn: ac

		annotation SummarizationSetBy = Automatic

	column cpi
		dataType: double
		formatString: 0.00
		lineageTag: 0200168b-944a-47fa-988a-0370954823e8
		summarizeBy: average
		sourceColumn: cpi

		annotation SummarizationSetBy = Automatic

	column spi
		dataType: double
		formatString: 0.00
		lineageTag: 8e4b67c2-d3dc-4198-b327-143a8e12b9a2
		summarizeBy: average
		sourceColumn: spi

		annotation SummarizationSetBy = Automatic

	column eac_cpi
		dataType: double
		formatString: #,##0
		lineageTag: aef0dd4f-4e3c-469f-9efa-9a2dcfa0371d
		summarizeBy: sum
		sourceColumn: eac_cpi

		annotation SummarizationSetBy = Automatic

	column eac_composite
		dataType: double
		formatString: #,##0
		lineageTag: 482412d9-7566-4b70-a97e-001da0fb063f
		summarizeBy: sum
		sourceColumn: eac_composite

		annotation SummarizationSetBy = Automatic

	column eac_weighted
		dataType: double
		formatString: #,##0
		lineageTag: 1c612cf8-5fda-4dae-869c-be529017e63f
		summarizeBy: sum
		sourceColumn: eac_weighted

		annotation SummarizationSetBy = Automatic

	column vac
		dataType: double
		formatString: #,##0
		lineageTag: bc9033ce-11c0-464e-ad80-e83b6f8b96f0
		summarizeBy: sum
		sourceColumn: vac

		annotation SummarizationSetBy = Automatic

	column tcpi
		dataType: double
		formatString: 0.00
		lineageTag: e2dc5175-aeab-4102-a7ed-47d58cf353b7
		summarizeBy: average
		sourceColumn: tcpi

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: c7d2f4fe-cf29-4f20-907b-9511d886ab3e
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition Fact_EVM_Snapshots-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Fact_EVM_Snapshots.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"reporting_period", type text},
				        {"snapshot_timestamp", type datetime},
				        {"project_id", type text},
				        {"bac", type number},
				        {"pv", type number},
				        {"ev", type number},
				        {"ac", type number},
				        {"cpi", type number},
				        {"spi", type number},
				        {"eac_cpi", type number},
				        {"eac_composite", type number},
				        {"eac_weighted", type number},
				        {"vac", type number},
				        {"tcpi", type number},
				        {"status", type text}
				    })
				in
				    #"Changed Type"
