table Fact_Travel_Audit
	lineageTag: 621731c1-d2dc-4182-ba3a-4809896f0b8c

	column Reise_ID
		dataType: string
		lineageTag: 2c75d4fb-9e1f-4402-bb88-8f23169b7106
		summarizeBy: none
		sourceColumn: Reise_ID

		annotation SummarizationSetBy = Automatic

	column Ansatt
		dataType: string
		lineageTag: d9ccf437-fb5a-4f16-8c20-b9a356aebc3a
		summarizeBy: none
		sourceColumn: Ansatt

		annotation SummarizationSetBy = Automatic

	column Dato
		dataType: string
		lineageTag: 85ebf123-a217-4ed5-ab8a-58e675775c01
		summarizeBy: none
		sourceColumn: Dato

		annotation SummarizationSetBy = Automatic

	column Formaal
		dataType: string
		lineageTag: 123d658c-363b-4167-95f8-259cb9d7f3d6
		summarizeBy: none
		sourceColumn: Formaal

		annotation SummarizationSetBy = Automatic

	column Belop_NOK
		dataType: double
		formatString: #,##0
		lineageTag: 4cff68ab-256b-432c-97d7-344e66040cde
		summarizeBy: sum
		sourceColumn: Belop_NOK

		annotation SummarizationSetBy = Automatic

	column Maltid_Dekket
		dataType: string
		lineageTag: 9162cb3f-3681-4712-a7df-25d82d326fee
		summarizeBy: none
		sourceColumn: Maltid_Dekket

		annotation SummarizationSetBy = Automatic

	column Fradrag_Utfort
		dataType: boolean
		lineageTag: e17717ec-f395-439f-9cea-ff3c4af98c17
		summarizeBy: none
		sourceColumn: Fradrag_Utfort

		annotation SummarizationSetBy = Automatic

	column Km_Godtgjorelse
		dataType: int64
		formatString: #,##0
		lineageTag: 22b29390-c1a6-4ddd-912d-f55acb189dbe
		summarizeBy: sum
		sourceColumn: Km_Godtgjorelse

		annotation SummarizationSetBy = Automatic

	column Kvittering_Vedlagt
		dataType: boolean
		lineageTag: a2615c60-0198-43f3-9e44-16050488bf25
		summarizeBy: none
		sourceColumn: Kvittering_Vedlagt

		annotation SummarizationSetBy = Automatic

	column BDM_ID
		dataType: string
		lineageTag: 79672801-0409-43ce-9712-61647a5cbbfd
		summarizeBy: none
		sourceColumn: BDM_ID

		annotation SummarizationSetBy = Automatic

	column Attestant_ID
		dataType: string
		lineageTag: 673bf95f-026f-4bd6-ab11-802942084337
		summarizeBy: none
		sourceColumn: Attestant_ID

		annotation SummarizationSetBy = Automatic

	column Km_Rute_Beskrevet
		dataType: boolean
		lineageTag: b3a3ca36-e683-42f1-8969-a43515cb2fe6
		summarizeBy: none
		sourceColumn: Km_Rute_Beskrevet

		annotation SummarizationSetBy = Automatic

	column Avvik_Beskrivelse
		dataType: string
		lineageTag: 2edeb99e-4c3f-4c7c-9a2b-5fa75e0c468c
		summarizeBy: none
		sourceColumn: Avvik_Beskrivelse

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: b5117761-764b-4dc8-9757-629a1f5fa7f2
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition Fact_Travel_Audit-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Fact_Travel_Audit.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"Reise_ID", type text},
				        {"Ansatt", type text},
				        {"Dato", type text},
				        {"Formaal", type text},
				        {"Belop_NOK", type number},
				        {"Maltid_Dekket", type text},
				        {"Fradrag_Utfort", type logical},
				        {"Km_Godtgjorelse", Int64.Type},
				        {"Kvittering_Vedlagt", type logical},
				        {"BDM_ID", type text},
				        {"Attestant_ID", type text},
				        {"Km_Rute_Beskrevet", type logical},
				        {"Avvik_Beskrivelse", type text},
				        {"Status", type text}
				    })
				in
				    #"Changed Type"

