table Fact_Travel_Audit
	lineageTag: 87ddaf55-134c-4c38-8df7-1f4d28c54c66

	column Reise_ID
		dataType: string
		lineageTag: 74e30ca7-d1fd-444a-afa7-9610251bce5f
		summarizeBy: none
		sourceColumn: Reise_ID

		annotation SummarizationSetBy = Automatic

	column Ansatt
		dataType: string
		lineageTag: 499b9e70-a13f-4722-bb73-31b276e68f1e
		summarizeBy: none
		sourceColumn: Ansatt

		annotation SummarizationSetBy = Automatic

	column Dato
		dataType: string
		lineageTag: 66525e3a-e940-4292-960d-9eac74b7495e
		summarizeBy: none
		sourceColumn: Dato

		annotation SummarizationSetBy = Automatic

	column Formaal
		dataType: string
		lineageTag: dd055aa0-eb4f-49f8-8982-7b3fe68ab328
		summarizeBy: none
		sourceColumn: Formaal

		annotation SummarizationSetBy = Automatic

	column Belop_NOK
		dataType: double
		formatString: #,##0
		lineageTag: 55551ad3-983c-4bfb-876e-8b5a11134e2f
		summarizeBy: sum
		sourceColumn: Belop_NOK

		annotation SummarizationSetBy = Automatic

	column Maltid_Dekket
		dataType: string
		lineageTag: a25cd350-663d-4cf8-9b73-ec995c6e7bce
		summarizeBy: none
		sourceColumn: Maltid_Dekket

		annotation SummarizationSetBy = Automatic

	column Fradrag_Utfort
		dataType: boolean
		lineageTag: 871ec400-c4d4-4555-817c-aab756b12ab9
		summarizeBy: none
		sourceColumn: Fradrag_Utfort

		annotation SummarizationSetBy = Automatic

	column Km_Godtgjorelse
		dataType: int64
		formatString: #,##0
		lineageTag: 0b1d50f0-4f3d-46d8-851f-4bfe94b20080
		summarizeBy: sum
		sourceColumn: Km_Godtgjorelse

		annotation SummarizationSetBy = Automatic

	column Kvittering_Vedlagt
		dataType: boolean
		lineageTag: 8d365355-fd7d-4e62-8026-117458bb2bf2
		summarizeBy: none
		sourceColumn: Kvittering_Vedlagt

		annotation SummarizationSetBy = Automatic

	column BDM_ID
		dataType: string
		lineageTag: 23801f72-60a7-4f9d-b5d7-b72d521624bb
		summarizeBy: none
		sourceColumn: BDM_ID

		annotation SummarizationSetBy = Automatic

	column Attestant_ID
		dataType: string
		lineageTag: a0cc3977-e257-4f3b-9e28-e17a29eda1dc
		summarizeBy: none
		sourceColumn: Attestant_ID

		annotation SummarizationSetBy = Automatic

	column Km_Rute_Beskrevet
		dataType: boolean
		lineageTag: afa4760a-ee2f-4afc-935e-9f39fa807e80
		summarizeBy: none
		sourceColumn: Km_Rute_Beskrevet

		annotation SummarizationSetBy = Automatic

	column Avvik_Beskrivelse
		dataType: string
		lineageTag: 630ee0ef-4c0d-4b97-a026-60c6b45395e2
		summarizeBy: none
		sourceColumn: Avvik_Beskrivelse

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: d334a41e-9ac7-4654-ba56-8fed6602ec41
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition Fact_Travel_Audit-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Fact_Travel_Audit.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"Reise_ID", type text},
				        {"Ansatt", type text},
				        {"Dato", type text},
				        {"Formaal", type text},
				        {"Belop_NOK", type number},
				        {"Maltid_Dekket", type text},
				        {"Fradrag_Utfort", type logical},
				        {"Km_Godtgjorelse", Int64.Type},
				        {"Kvittering_Vedlagt", type logical},
				        {"BDM_ID", type text},
				        {"Attestant_ID", type text},
				        {"Km_Rute_Beskrevet", type logical},
				        {"Avvik_Beskrivelse", type text},
				        {"Status", type text}
				    })
				in
				    #"Changed Type"
