table Fact_UBW_Audit
	lineageTag: ada2681f-0b4d-4600-b2c0-df88bec4e4ba

	column transaksjon_id
		dataType: string
		lineageTag: c51c1ecd-e8aa-431c-a5d6-46a3f182f3be
		summarizeBy: none
		sourceColumn: transaksjon_id

		annotation SummarizationSetBy = Automatic

	column konto
		dataType: string
		lineageTag: 5d620ccb-1c35-4c90-a32f-5f2b1bc19d0c
		summarizeBy: none
		sourceColumn: konto

		annotation SummarizationSetBy = Automatic

	column beskrivelse
		dataType: string
		lineageTag: 1f825dda-424e-4dc7-9261-b145a21daa5b
		summarizeBy: none
		sourceColumn: beskrivelse

		annotation SummarizationSetBy = Automatic

	column belop_nok
		dataType: double
		formatString: #,##0
		lineageTag: 637118cb-5025-437d-af96-921dacc9e60a
		summarizeBy: sum
		sourceColumn: belop_nok

		annotation SummarizationSetBy = Automatic

	column bdm_id
		dataType: string
		lineageTag: 6a661b43-a704-4293-9077-2ba11e9029a8
		summarizeBy: none
		sourceColumn: bdm_id

		annotation SummarizationSetBy = Automatic

	column attestant_id
		dataType: string
		lineageTag: ef9a13a2-225a-4212-befb-464c2fce8b11
		summarizeBy: none
		sourceColumn: attestant_id

		annotation SummarizationSetBy = Automatic

	column kvittering_vedlagt
		dataType: int64
		lineageTag: 1afd2c27-ca86-4178-99bb-cb2cd2fabc5a
		summarizeBy: none
		sourceColumn: kvittering_vedlagt

		annotation SummarizationSetBy = Automatic

	column formaal
		dataType: string
		lineageTag: 1b42a978-9820-40af-ba05-ed8573f803dd
		summarizeBy: none
		sourceColumn: formaal

		annotation SummarizationSetBy = Automatic

	column Kontrollflagg
		dataType: string
		lineageTag: 6da4c7ca-dfa6-4c07-92ca-5e48d309c1f2
		summarizeBy: none
		sourceColumn: Kontrollflagg

		annotation SummarizationSetBy = Automatic

	partition Fact_UBW_Audit-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Fact_UBW_Audit.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"transaksjon_id", type text},
				        {"konto", type text},
				        {"beskrivelse", type text},
				        {"belop_nok", type number},
				        {"bdm_id", type text},
				        {"attestant_id", type text},
				        {"kvittering_vedlagt", Int64.Type},
				        {"formaal", type text},
				        {"Kontrollflagg", type text}
				    })
				in
				    #"Changed Type"
