table Fact_UBW_Audit
	lineageTag: 584ef0c7-a0a4-4538-95df-7fd7a7e60584

	column transaksjon_id
		dataType: string
		lineageTag: 8e40a46a-3ffc-4ffd-b84b-756f45c4578b
		summarizeBy: none
		sourceColumn: transaksjon_id

		annotation SummarizationSetBy = Automatic

	column konto
		dataType: string
		lineageTag: b8daf0e7-e087-4fc8-ae0c-9cbcc1764e6a
		summarizeBy: none
		sourceColumn: konto

		annotation SummarizationSetBy = Automatic

	column beskrivelse
		dataType: string
		lineageTag: 5fcbf751-9f65-4c5b-8dc5-d6f16a255b7f
		summarizeBy: none
		sourceColumn: beskrivelse

		annotation SummarizationSetBy = Automatic

	column belop_nok
		dataType: double
		formatString: #,##0
		lineageTag: be1e4b6b-d3d6-45aa-9d9b-f7ee1f0d222c
		summarizeBy: sum
		sourceColumn: belop_nok

		annotation SummarizationSetBy = Automatic

	column bdm_id
		dataType: string
		lineageTag: 0c83ddd8-e778-4e9e-ad16-59b784881a11
		summarizeBy: none
		sourceColumn: bdm_id

		annotation SummarizationSetBy = Automatic

	column attestant_id
		dataType: string
		lineageTag: bb427495-9a68-47d0-953a-625f74137fbe
		summarizeBy: none
		sourceColumn: attestant_id

		annotation SummarizationSetBy = Automatic

	column kvittering_vedlagt
		dataType: int64
		lineageTag: 312c50ed-d96b-48fe-bd26-50c41802249b
		summarizeBy: none
		sourceColumn: kvittering_vedlagt

		annotation SummarizationSetBy = Automatic

	column formaal
		dataType: string
		lineageTag: fd52bf76-f5f0-4a25-9552-b374c606419b
		summarizeBy: none
		sourceColumn: formaal

		annotation SummarizationSetBy = Automatic

	column Kontrollflagg
		dataType: string
		lineageTag: 74fd1687-1a8b-4c2d-ad40-2a9730a877bf
		summarizeBy: none
		sourceColumn: Kontrollflagg

		annotation SummarizationSetBy = Automatic

	partition Fact_UBW_Audit-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Fact_UBW_Audit.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"transaksjon_id", type text},
				        {"konto", type text},
				        {"beskrivelse", type text},
				        {"belop_nok", type number},
				        {"bdm_id", type text},
				        {"attestant_id", type text},
				        {"kvittering_vedlagt", Int64.Type},
				        {"formaal", type text},
				        {"Kontrollflagg", type text}
				    })
				in
				    #"Changed Type"
