table Fact_Travel_Audit
	lineageTag: 30e4ed06-8237-4724-a942-c3663fa64e01

	column Reise_ID
		dataType: string
		lineageTag: f238c9d8-1bc5-478f-86e0-e675917e85ab
		summarizeBy: none
		sourceColumn: Reise_ID

		annotation SummarizationSetBy = Automatic

	column Ansatt
		dataType: string
		lineageTag: dd08fa93-74cf-46c8-a51e-1549246993f5
		summarizeBy: none
		sourceColumn: Ansatt

		annotation SummarizationSetBy = Automatic

	column Dato
		dataType: string
		lineageTag: c5e3cdf9-9ae4-4a4f-8436-0d1ea8b2e9eb
		summarizeBy: none
		sourceColumn: Dato

		annotation SummarizationSetBy = Automatic

	column Formaal
		dataType: string
		lineageTag: 3fe0762c-e200-47f7-9b33-117eed507ee1
		summarizeBy: none
		sourceColumn: Formaal

		annotation SummarizationSetBy = Automatic

	column Belop_NOK
		dataType: double
		formatString: #,##0
		lineageTag: 60709683-4831-4e9c-9762-2b602460c030
		summarizeBy: sum
		sourceColumn: Belop_NOK

		annotation SummarizationSetBy = Automatic

	column Maltid_Dekket
		dataType: string
		lineageTag: 83c3fdee-f38d-4207-b6aa-97f26e4ca029
		summarizeBy: none
		sourceColumn: Maltid_Dekket

		annotation SummarizationSetBy = Automatic

	column Fradrag_Utfort
		dataType: boolean
		lineageTag: c76d7a8d-95f1-4772-bc63-0fb787942982
		summarizeBy: none
		sourceColumn: Fradrag_Utfort

		annotation SummarizationSetBy = Automatic

	column Km_Godtgjorelse
		dataType: int64
		formatString: #,##0
		lineageTag: 2ee14834-2d7d-4474-953f-ab3c4d08e31d
		summarizeBy: sum
		sourceColumn: Km_Godtgjorelse

		annotation SummarizationSetBy = Automatic

	column Kvittering_Vedlagt
		dataType: boolean
		lineageTag: b3f41683-7552-455e-a0ea-e99afa0b69af
		summarizeBy: none
		sourceColumn: Kvittering_Vedlagt

		annotation SummarizationSetBy = Automatic

	column BDM_ID
		dataType: string
		lineageTag: 78ea096e-6aec-4c04-b041-7e7701ef085c
		summarizeBy: none
		sourceColumn: BDM_ID

		annotation SummarizationSetBy = Automatic

	column Attestant_ID
		dataType: string
		lineageTag: c76aa66c-c3a5-4dac-9716-58ea58a627dc
		summarizeBy: none
		sourceColumn: Attestant_ID

		annotation SummarizationSetBy = Automatic

	column Km_Rute_Beskrevet
		dataType: boolean
		lineageTag: ab8f4bce-3420-4508-bb19-91e3a6ba2149
		summarizeBy: none
		sourceColumn: Km_Rute_Beskrevet

		annotation SummarizationSetBy = Automatic

	column Avvik_Beskrivelse
		dataType: string
		lineageTag: 4c240317-4bac-40c7-9b2b-18c86673506e
		summarizeBy: none
		sourceColumn: Avvik_Beskrivelse

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 5e10fbd6-115b-4333-94ce-c256bc84740b
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition Fact_Travel_Audit-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Fact_Travel_Audit.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"Reise_ID", type text},
				        {"Ansatt", type text},
				        {"Dato", type text},
				        {"Formaal", type text},
				        {"Belop_NOK", type number},
				        {"Maltid_Dekket", type text},
				        {"Fradrag_Utfort", type logical},
				        {"Km_Godtgjorelse", Int64.Type},
				        {"Kvittering_Vedlagt", type logical},
				        {"BDM_ID", type text},
				        {"Attestant_ID", type text},
				        {"Km_Rute_Beskrevet", type logical},
				        {"Avvik_Beskrivelse", type text},
				        {"Status", type text}
				    })
				in
				    #"Changed Type"
