table Dim_Project
	lineageTag: 47e21a62-cff0-4eea-a2df-6ee657423d35

	column project_id
		dataType: string
		lineageTag: db512ee5-f3cf-4c64-98f7-c26ef084ae1c
		summarizeBy: none
		sourceColumn: project_id

		annotation SummarizationSetBy = Automatic

	column project_name
		dataType: string
		lineageTag: f1b29fbd-1cf1-4cb8-93b3-8af6e5ffe73d
		summarizeBy: none
		sourceColumn: project_name

		annotation SummarizationSetBy = Automatic

	column bac
		dataType: double
		formatString: #,##0
		lineageTag: 9b01bdd0-c0db-4723-92e1-c213f59b6bb1
		summarizeBy: sum
		sourceColumn: bac

		annotation SummarizationSetBy = Automatic

	column pv
		dataType: double
		formatString: #,##0
		lineageTag: 457b42d5-a0ec-405d-98fc-afcdf32fc241
		summarizeBy: sum
		sourceColumn: pv

		annotation SummarizationSetBy = Automatic

	column ev
		dataType: double
		formatString: #,##0
		lineageTag: 147cc791-1e49-451d-9e70-ca6ba1a30e8c
		summarizeBy: sum
		sourceColumn: ev

		annotation SummarizationSetBy = Automatic

	column ac
		dataType: double
		formatString: #,##0
		lineageTag: 02b2e077-ce57-4150-8654-0d77bade9e9d
		summarizeBy: sum
		sourceColumn: ac

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: c0c40294-cbd4-438f-9683-062f2c7ca379
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition Dim_Project-partition = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents("C:\Users\frank\Desktop\UIA-Controller\data\staging\parquet\Dim_Project.parquet")),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				        {"project_id", type text},
				        {"project_name", type text},
				        {"bac", type number},
				        {"pv", type number},
				        {"ev", type number},
				        {"ac", type number},
				        {"status", type text}
				    })
				in
				    #"Changed Type"
